name: Build veusz

on:
    # push:
    # pull_request:
    workflow_dispatch:

jobs:
  build_wheels:
    name: Build veusz-${{ matrix.veusz-version }} wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          # - ubuntu-latest
          - windows-latest
          # - macos-latest
        python-version:
          - 3.6
          - 3.7
          - 3.8
          - 3.9
          - 3.10
          - 3.11
        include:
          - veusz-version: 3.6.2

    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v3
        with:
            repository: 'veusz/veusz'
            ref: "veusz-${{ matrix.veusz-version }}"

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: "${{ runner.os }}-QtCache"

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
          archives: 'qtsvg'

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies by pip
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install -r requirements.txt

      - name: Build Wheels
        run: |
          python setup.py sdist bdist_wheel

      - name: Upload Wheels
        uses: actions/upload-artifact@v2
        with:
          name: "${{ runner.os }}-veusz-${{ matrix.veusz-version }}-wheels"
          path: dist/*.whl
